repos:
  # Basic sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [ "--allow-multiple-documents" ]
        exclude: ^charts/.*/templates/
      - id: check-json
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: detect-aws-credentials

  # OpenTofu/Terraform ecosystem
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        name: tofu_fmt
        entry: tofu
        language: system
        args: [ "fmt", "-recursive" ]
      - id: terraform_docs
        args: [ 'args=-recursive' ]

  # Commit message linting (Conventional Commits style)
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
